version: '3.8'
services:
  emqx-enterprise:
    image: emqx/emqx-enterprise:5.0.3
    healthcheck:
      test: ["CMD", "emqx", "ping"]
      interval: 5s
      timeout: 10s
      retries: 12
    ports:
      - 1883:1883
      - 18083:18083
    volumes:
      - $PWD/emqx/cluster.hocon:/opt/emqx/data/configs/cluster.hocon
      - $PWD/emqx/api_secret:/opt/emqx/data/api_secret
    environment:
      EMQX_DASHBOARD__BOOTSTRAP_USERS_FILE: '"/opt/emqx/data/api_secret"'

  emqx-exporter:
    image: emqx/emqx-exporter
    ports:
      - 8085:8085
    command:
      - '--emqx.nodes=emqx-enterprise:18083'
      - '--emqx.auth-username=76668f8a2003d597'
      - '--emqx.auth-password=CRCDB6lxxzN58e5HoD82llBC0Erg1TVZIAUsdTjPU7N'
    depends_on:
      emqx-enterprise:
        condition: service_healthy

  mqttx-pub:
    image: emqx/mqttx-cli:v1.9.3
    command:
      - /bin/sh
      - -c
      - |
        mqttx simulate -sc IEM -c 10 -h emqx-enterprise
    depends_on:
      emqx-enterprise:
        condition: service_healthy

  mqttx-sub:
    image: emqx/mqttx-cli:v1.9.3
    command:
      - /bin/sh
      - -c
      - |
        mqttx sub -t 'mqttx/simulate/#' -v -h emqx-enterprise
    depends_on:
      emqx-enterprise:
        condition: service_healthy

  timescaledb:
    image: timescale/timescaledb:latest-pg12
    ports:
      - 5432:5432
    volumes:
      - $PWD/create-table.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=public
      - POSTGRES_DB=iot_data

  prometheus:
    image: prom/prometheus:v2.44.0
    ports:
      - 9090:9090
    volumes:
      - $PWD/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.3.2
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=public
    volumes:
      - $PWD/emqx-exporter/config/grafana-template/EMQX5-enterprise:/grafana-dashboard-emqx5-ee
      - $PWD/grafana-dashboards:/grafana-dashboard-IEM
      - $PWD/grafana-provisioning/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - $PWD/grafana-provisioning/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    depends_on:
      emqx-enterprise:
        condition: service_healthy
      timescaledb:
        condition: service_started

networks:
  mqtt-to-timescaledb:
    name: mqtt-to-timescaledb
