{
 "title": "dashboard1",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "南一区空调 - 今日能耗",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "nhjk_nan1",
     "select": [
      [
       { "params": [ "energy_ac1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "南二区空调 - 今日能耗",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "nhjk_nan2",
     "select": [
      [
       { "params": [ "energy_ac2" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "北一区空调 - 今日能耗",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "nhjk_bei1",
     "select": [
      [
       { "params": [ "energy_ac3" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "空压机1# - 今日能耗",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "nhjk_nan1",
     "select": [
      [
       { "params": [ "energy_kyj1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "空压机2# - 今日能耗",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "nhjk_nan2",
     "select": [
      [
       { "params": [ "energy_kyj2" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "空压机3# - 今日能耗",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "nhjk_bei1",
     "select": [
      [
       { "params": [ "energy_kyj3" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "今日厂区空调能耗分布",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "南一区空调",
     "limit": "1",
     "measurement": "nhjk_nan1",
     "query": "SELECT last(\"energy_ac1\") FROM \"nhjk_nan1\"  ",
     "select": [
      [
       { "params": [ "energy_light1" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "南二区空调",
     "measurement": "nhjk_nan2",
     "query": "SELECT last(\"energy_ac2\")  FROM \"nhjk_nan2\" ",
     "select": [
      [
       { "params": [ "energy_light2" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "北一区空调",
     "measurement": "nhjk_bei1",
     "query": "SELECT last(\"energy_ac3\") FROM \"nhjk_bei1\" ",
     "select": [
      [
       { "params": [ "energy_light3" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "今日厂区照明能耗分布",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "南一区照明",
     "limit": "1",
     "measurement": "nhjk_nan1",
     "query": "SELECT last(\"energy_light1\") FROM \"nhjk_nan1\"  ",
     "select": [
      [
       { "params": [ "energy_light1" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "南二区照明",
     "measurement": "nhjk_nan2",
     "query": "SELECT last(\"energy_light2\")  FROM \"nhjk_nan2\" ",
     "select": [
      [
       { "params": [ "energy_light2" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "北一区照明",
     "measurement": "nhjk_bei1",
     "query": "SELECT last(\"energy_light3\") FROM \"nhjk_bei1\" ",
     "select": [
      [
       { "params": [ "energy_light3" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "今日厂区设备能耗分布",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "南一区设备",
     "limit": "1",
     "measurement": "nhjk_nan1",
     "query": "SELECT last(\"energy_kyj1\") FROM \"nhjk_nan1\"  ",
     "select": [
      [
       { "params": [ "energy_light1" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "南二区设备",
     "measurement": "nhjk_nan2",
     "query": "SELECT last(\"energy_kyj2\")  FROM \"nhjk_nan2\" ",
     "select": [
      [
       { "params": [ "energy_light2" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "北一区设备",
     "measurement": "nhjk_bei1",
     "query": "SELECT last(\"energy_kyj3\") FROM \"nhjk_bei1\" ",
     "select": [
      [
       { "params": [ "energy_light3" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "南一区 - 本周能耗监控",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "空调",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nhjk_nan1",
     "query": "select max(\"energy_ac1\") from \"nhjk_nan1\" where time > now() - 7d GROUP BY time(1d) TZ('Asia/Shanghai')",
     "select": [
      [
       { "params": [ "energy_ac1" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "照明",
     "query": "select max(\"energy_light1\") from \"nhjk_nan1\" where time > now() - 7d GROUP BY time(1d) TZ('Asia/Shanghai')"
    },
    {
     "alias": "空压机",
     "query": "select max(\"energy_kyj1\") from \"nhjk_nan1\" where time > now() - 7d GROUP BY time(1d) TZ('Asia/Shanghai')"
    }
   ]
  },
  {
   "title": "南二区 - 本周能耗监控",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "空调",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nhjk_nan1",
     "query": "select max(\"energy_ac2\") from \"nhjk_nan2\" where time > now() - 7d GROUP BY time(1d) TZ('Asia/Shanghai')",
     "select": [
      [
       { "params": [ "energy_ac1" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "照明",
     "query": "select max(\"energy_light2\") from \"nhjk_nan2\" where time > now() - 7d GROUP BY time(1d) TZ('Asia/Shanghai')"
    },
    {
     "alias": "空压机",
     "query": "select max(\"energy_kyj2\") from \"nhjk_nan2\" where time > now() - 7d GROUP BY time(1d) TZ('Asia/Shanghai')"
    }
   ]
  }
 ]
}