{
 "title": "Energy Monitoring data",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_POSTGRESQL", "query": "postgres" },
   {
    "name": "factory",
    "label": "Factory",
    "query": "SELECT factory FROM energy_log group by factory"
   }
  ]
 },
 "panels": [
  {
   "title": "Energy Overview",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', \"timestamp\") AS \"time\",\n  SUM(\n    air_compressor_1 + air_compressor_2 + lighting + cooling_equipment + heating_equipment + conveyor + coating_equipment + inspection_equipment + welding_equipment + packaging_equipment + cutting_equipment\n  ) AS total_energy,\n  SUM(air_compressor_1) AS air_compressor_1,\n  SUM(air_compressor_2) AS air_compressor_2,\n  SUM(lighting) AS lighting,\n  SUM(cooling_equipment) AS cooling_equipment,\n  SUM(heating_equipment) AS heating_equipment,\n  SUM(conveyor) AS conveyor,\n  SUM(coating_equipment) AS coating_equipment,\n  SUM(inspection_equipment) AS inspection_equipment,\n  SUM(welding_equipment) AS welding_equipment,\n  SUM(packaging_equipment) AS packaging_equipment,\n  SUM(cutting_equipment) AS cutting_equipment\nFROM\n  energy_log\nGROUP BY\n  \"time\",\n  air_compressor_1,\n  air_compressor_2,\n  lighting,\n  cooling_equipment,\n  heating_equipment,\n  conveyor,\n  coating_equipment,\n  inspection_equipment,\n  welding_equipment,\n  packaging_equipment,\n  cutting_equipment\nORDER BY\n  \"time\""
    }
   ]
  },
  {
   "title": "Energy Distribution Top 10 - Equipment",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', \"timestamp\") AS \"time\",\n  SUM(air_compressor_1) AS \"air_compressor_1\",\n  SUM(air_compressor_2) AS \"air_compressor_2\",\n  SUM(lighting) AS \"lighting\",\n  SUM(cooling_equipment) AS \"cooling_equipment\",\n  SUM(heating_equipment) AS \"heating_equipment\",\n  SUM(conveyor) AS \"conveyor\",\n  SUM(coating_equipment) AS \"coating_equipment\",\n  SUM(inspection_equipment) AS \"inspection_equipment\",\n  SUM(welding_equipment) AS \"welding_equipment\",\n  SUM(packaging_equipment) AS \"packaging_equipment\",\n  SUM(cutting_equipment) AS \"cutting_equipment\"\nFROM\n  energy_log\nWHERE\n  factory IN ($factory)\nGROUP BY\n  \"time\"\nORDER BY\n  \"time\"\n"
    }
   ]
  },
  {
   "title": "Energy Distribution Top 10 - Factory",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(\n    air_compressor_1 + air_compressor_2 + lighting + cooling_equipment + heating_equipment + conveyor + coating_equipment + inspection_equipment + welding_equipment + packaging_equipment + cutting_equipment\n  ) AS total_energy,\n  factory\nFROM\n  energy_log\nGROUP BY\n  factory\norder by\n  total_energy desc"
    }
   ]
  },
  {
   "title": "Total Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(\n    air_compressor_1 + air_compressor_2 + lighting + cooling_equipment + heating_equipment + conveyor + coating_equipment + inspection_equipment + welding_equipment + packaging_equipment + cutting_equipment\n  ) AS total_energy,\n  time_bucket('$__interval', \"timestamp\") AS \"time\"\nFROM\n  energy_log\nWHERE factory in ($factory)\nGROUP BY\n  time"
    }
   ]
  },
  {
   "title": "Air Compressor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(air_compressor_1) as air_compressor_1,\n  SUM(air_compressor_2) as air_compressor_2,\n  time_bucket('$__interval', \"timestamp\") AS \"time\"\nFROM\n  energy_log\nWHERE\n  factory IN ($factory)\nGROUP BY\n  \"time\""
    }
   ]
  }
 ]
}